- name: Copy
  copy:
    src: ../../files/collect.sh
    dest: /tmp
    mode: '0755'

- name: shell
  shell: bash /tmp/collect.sh
  register: result
  changed_when: false
- name: show stdout
  debug:
    msg: "{{ result.stdout_lines }}"

- name: remove file
  file: 
    path: /tmp/collect.sh
    state: absent