- name: Git checkout
  git:
    repo: https://github.com/go-delve/delve.git
    dest: /tmp

- name: setup
  shell: sudo -u isucon bash -lc "go install github.com/go-delve/delve/cmd/dlv"
  args:
    chdir: "/tmp/delve"