- name: shell
  become: true
  shell: mysql -u isuconp -pisuconp isuconp -e "alter table comments add index post_index(post_id, created_at DESC);"
  ignore_errors: yes

- name: shell
  shell: mysql -u isuconp -pisuconp isuconp -e "alter table posts add index posts_order_idx (created_at DESC);"
  ignore_errors: yes

- name: shell
  shell: mysql -u isuconp -pisuconp isuconp -e "ALTER TABLE `comments` ADD INDEX `idx_user_id` (`user_id`);"
  ignore_errors: yes

- name: shell
  shell: mysql -u isuconp -pisuconp isuconp -e "ALTER TABLE `posts` ADD INDEX `posts_user_idx` (`user_id`,`created_at` DESC);"
  ignore_errors: yes

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted
  become: yes

- name: shell
  shell: bash -lc "go get github.com/redis/go-redis/v8"
  args:
    chdir: "{{ home_dir }}/{{ isu_dir_name }}/webapp/golang/"
  ignore_errors: yes

- name: isu-go is restarted
  systemd:
    name: isu-go
    state: restarted
  become: yes